### ISSUE TITLE
Fill in more details about yourself

### ISSUE THREAD

**Issue by adamg6775** [NurAbas/nurabas#1]
For your repostorie you could fill in more about yourself so if a person is looking at this they could get a bigger picture about you and what you do.

For example, instead of this **programming I'm [Nur], a [Your Role/Title] passionate about [Your Interests]. Welcome to my GitHub profile!**

You could do this **Hi I'm Nur, I´m a Data student learning about programming and Data infrastructure and by 2025 I will be a certified Network technician. I´m passionate about ...** 

 Welcome to my GitHub profile!**

Also for extra details you could add more details about your **skills** that you are learning in school and name some of the projects that you have been working on.

**Comment by NurAbas** [comment]
Thank you for the feedback
